### PR TITLE
Backport and crossBuild to 2.11

### PR DESCRIPTION
**Pull request by easel**

### CODE REVIEW

**Comment by mkotsur** [comment]
Thanks @easel !

**Comment by easel** [comment]
Thanks for the merge!

**Comment by mkotsur** [comment]
Hey @easel. The version 0.0.13 seems to be properly released for both versions of Scala, feel free to switch to it. 

I had to iterate a couple of times through `build.sbt` to get the whole process work properly and fully automatically :-) In case you're interested: c05bd6115dc0cefad00ffd6b387a7f5c2e4f8e5f...fbd1f652b499f149ed97b017bb5284f989d13b6e

**Comment by mkotsur** [comment]
@easel are you still using the lib with Scala 2.11? I'm considering to drop support for new versions.

**Comment by easel** [comment]
I'm still trying to hold onto my cross-build since spark hasn't moved over, but the rest of my "endpoints" are on 2.12 so I think it's ok to drop it.

**Pull request merged**
